version:              '3'
# Tout ce qui est
services:
  # Volatile IDE Workspace :
  # should support hot reloading
  hot_ide_workspace:
    container_name: "pegasus_ide"
    image: pegasus-devops.io/ide:0.0.1
    build:
      context: oci/ide/
      args:
        # + ...
        - VERSION_KUBECTL=${VERSION_KUBECTL}
        - VERSION_HELM=${VERSION_HELM}
    environment:
      # + ...
      - GIT_USER_NAME=Jean-Baptiste-Lasselle
      - GIT_USER_EMAIL=jean.baptiste.lasselle.pegasus@gmail.com
      # what is going to be used to git config --global user.signingkey ${GIT_PGP_SIGNING_KEY}
      - GIT_GPG_SIGN=false
      - GIT_PGP_SIGNING_KEY=7B19A8E1574C2883
    # ---------------------------------------------
    # [docker [run|exec] -it ...]
    # stdin
    stdin_open:       true
    # stdout
    tty:              true
    # ---------------------------------------------
    # ports:
      # - 7999:8085/tcp
    # ---------------------------------------------
    volumes:
      - $PWD/:/bee/.workspace:rw
      - $PWD/.bee/.secrets:/bee/.secrets:rw
    networks:
      - ide_pipeline_net
    restart: always
    # depends_on:
      # - xxx
  secret_manager:
    container_name: "secretmanager"
    image: pegasus-devops.io/secretmanager:0.0.1
    build:
      context: oci/secrets/
      args:
        # + ...
        - OPERATOR_UID=${OPERATOR_UID}
        - OPERATOR_GID=${OPERATOR_GID}
    environment:
      # + ...
      - BBBBB=${DDDDD}
    # ---------------------------------------------
    # [docker [run|exec] -it ...]
    # stdin
    stdin_open:       true
    # stdout
    tty:              true
    # ---------------------------------------------
    # ports:
      # - 7999:8085/udp
    # ---------------------------------------------
    volumes:
      # --- #
      # where the secret manager will write secrets to other containers
      # --- #
      - secrets:/bee/.secrets:rw
      # --- #
      # The API token can be a gitlab, or a github, or a bitbucket, API TOKEN
      # Will be used to register SSH Key to git serrvice
      - $PWD/secret-manager:/bee/.topsecret/gitservice.api.token:ro
    networks:
      - ide_pipeline_net
    restart: always
    # depends_on:
      # - xxx

networks:
  ide_pipeline_net:
    driver: bridge

volumes:
  secrets:
    driver: local
    driver_opts:
      type: "none"
      o: "bind,rw"
      device: "/mnt/workspace/portus/secrets"
